dataset_config:
  textvqa:
      data_dir: ${env.data_dir}/datasets
      depth_first: false
      fast_read: false
      use_images: false
      use_features: true
      features:
        train:
        - textvqa/defaults/features/open_images/detectron.lmdb # needing to modify
        val:
        - textvqa/defaults/features/open_images/detectron.lmdb # needing to modify
        test:
        - textvqa/defaults/features/open_images/detectron.lmdb # needing to modify
      annotations:
        train:
        - textvqa/defaults/annotations/imdb_train_ocr_en.npy # needing to modify
        val:
        - textvqa/defaults/annotations/imdb_val_ocr_en.npy # needing to modify
        test:
        - textvqa/defaults/annotations/imdb_test_ocr_en.npy # needing to modify
      processors:
        text_processor:
          type: vocab
          params:
            max_length: 14
            vocab:
              type: intersected
              embedding_name: glove.6B.300d
              vocab_file: textvqa/defaults/extras/vocabs/vocabulary_100k.txt # needing to modify
            preprocessor:
              type: simple_sentence
              params: {}
        answer_processor:
          type: vqa_answer
          params:
            vocab_file: textvqa/defaults/extras/vocabs/answers_textvqa_8k.txt # needing to modify
            preprocessor:
              type: simple_word
              params: {}
            num_answers: 10
        context_processor:
          type: fasttext
          params:
            max_length: 50
            model_file: wiki.en.bin # needing to modify
        ocr_token_processor:
          type: simple_word
          params: {}
        bbox_processor:
          type: bbox
          params:
            max_length: 50
      return_features_info: true
      # Return OCR information
      use_ocr: true
      # Return spatial information of OCR tokens if present
      use_ocr_info: false
      use_order_vectors: false
