dataset_config:
  inforgraphicvqa:
      data_dir: ${env.data_dir}/datasets
      depth_first: false
      fast_read: false
      use_images: false
      use_features: true
      features:
        train:
        - inforgraphicvqa/defaults/features 
        val:
        - inforgraphicvqa/defaults/features  
        test:
        - inforgraphicvqa/defaults/features  
      annotations:
        train:
        - inforgraphicvqa/defaults/annotations/infoVQA_train_en.npy 
        val:
        - inforgraphicvqa/defaults/annotations/infoVQA_val_en.npy   
        test:
        - inforgraphicvqa/defaults/annotations/infoVQA_test_en.npy   
      processors:
        text_processor:
          type: vocab
          params:
            max_length: 14
            vocab:
              type: intersected
              embedding_name: glove.6B.300d
              vocab_file: inforgraphicvqa/defaults/extras/vocabs/vocabulary_100k.txt 
            preprocessor:
              type: simple_sentence
              params: {}
        answer_processor:
          type: vqa_answer
          params:
            vocab_file: inforgraphicvqa/defaults/extras/vocabs/answers_textvqa_8k.txt # needing to modify
            preprocessor:
              type: simple_word
              params: {}
            num_answers: 10
        context_processor:
          type: fasttext
          params:
            max_length: 50
            model_file: wiki.en.bin # needing to modify
        ocr_token_processor:
          type: simple_word
          params: {}
        bbox_processor:
          type: bbox
          params:
            max_length: 50
      return_features_info: true
      # Return OCR information
      use_ocr: true
      # Return spatial information of OCR tokens if present
      use_ocr_info: false
      use_order_vectors: false
